name = "vless-original-route-only"
main =  "-_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# ✅ ဒီ line ကို ထည့်ပါ
keep_vars = true

[vars]
# UUID ကို ဒီမှာ မထည့်ထားဘူး (Dashboard မှာ ထည့်ထားမယ်)
PROXYIP = ["pro.galaxytunnel.linkpc.net"; "blacknight.abrdns.com"; "privacy.bbroot.com"; "galax.cc.cd"; "net.galaxytunnel.linkpc.net"]
#PROXY_LIST_URL = "https://galaxytunnel.github.io/PROXYIP.txt"
DNS_RESOLVER_URL = "https://1.1.1.1.cloudflare-gateway.com/dns-query"
[vars]
# Optional. Valid values: direct or proxyip
DEFAULT_ROUTE = "direct"

# Optional hostname route rules.
# Example: *.google.com=proxyip,*.example.com=direct
ROUTES = "pro.galaxytunnel.linkpc.net"

# Set the existing worker credentials as secrets:
#   npx wrangler secret put UUID
#
# Optional runtime values can also be set as secrets/vars:
#   npx wrangler secret put PROXYIP
#   npx wrangler secret put TROJAN_PASS
#   npx wrangler secret put DNS_RESOLVER_URL
